name: Test

on:
  push:

  pull_request:
    types:
      - opened
      - synchronize

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: browser-actions/setup-chrome@latest
      - run: npm install -f
      - run: CHROME_BIN=$(which chrome) make test
        env:
          TS_NODE_COMPILER_OPTIONS: '{"module":"commonjs"}'
